### ISSUE TITLE
video_demo.py  KeyError: 'extri'

### ISSUE THREAD

**Issue by Pepslee** [facebookresearch/vggsfm#109]
I`m trying to run video_demo.py with window_size=6, I have only 8GB of memory

video_demo.yaml
``` yaml
hydra:
    run:
        dir: .


query_by_midpoint: True
shared_camera: True
camera_type: "SIMPLE_RADIAL"   # optional: ["SIMPLE_PINHOLE", "SIMPLE_RADIAL"]
max_query_pts: 1024

init_window_size: 6
window_size: 6
joint_BA_interval: 6
grid_based_sample: False

##########################


model_name: "vggsfm_v2_0_0"

seed: 0
img_size: 1024


debug: False


center_order: False
mixed_precision: fp16
extract_color: True
filter_invalid_frame: True

comple_nonvis: True
query_frame_num: 3
robust_refine: 2
BA_iters: 1

fine_tracking: True

load_gt: False
viz_visualize: False
gr_visualize: False

fmat_thres: 4.0
max_reproj_error: 4.0
init_max_reproj_error: 4.0

dense_depth: False

avg_pose: True

save_to_disk: True
SCENE_DIR: examples/kitchen

resume_ckpt:  ckpt/vggsfm_v2_0_0.bin
auto_download_ckpt: True

query_method: "aliked"

use_poselib: True

shift_point2d_to_original_res: False

make_reproj_video: False

visual_tracks: False
visual_query_points: False
visual_dense_point_cloud: False

query_by_interval: False

concat_extra_points: False
extra_pt_pixel_interval: -1
extra_by_neighbor: -1


MODEL:
    _target_: vggsfm.models.VGGSfM

    TRACK:
        _target_: vggsfm.models.TrackerPredictor

        efficient_corr: False

        COARSE:
            stride: 4
            down_ratio: 2
            FEATURENET:
                _target_: vggsfm.models.BasicEncoder

            PREDICTOR:
                _target_: vggsfm.models.BaseTrackerPredictor

        FINE:
            FEATURENET:
                _target_: vggsfm.models.ShallowEncoder


            PREDICTOR:
                _target_: vggsfm.models.BaseTrackerPredictor
                depth: 4
                corr_levels: 3
                corr_radius: 3
                latent_dim: 32
                hidden_size: 256
                fine: True
                use_spaceatt: False

    CAMERA:
        _target_: vggsfm.models.CameraPredictor


    TRIANGULAE:
        _target_: vggsfm.models.Triangulator    



```

``` shell
python video_demo.py SCENE_DIR=/home/user/Videos/test/cut/IMG_3135_cut_output_25fps gr_visualize=True visual_tracks=True shared_camera=True query_frame_num=8 camera_type=SIMPLE_RADIAL center_order=False
/home/user/PycharmProjects/vggsfm/dependency/LightGlue/lightglue/lightglue.py:24: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Poselib is available
Poselib is available
PyTorch3d is not available. Please disable visdom.
/home/user/PycharmProjects/vggsfm/video_demo.py:18: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="cfgs/", config_name="video_demo")
/home/user/miniconda3/lib/python3.12/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
Model Config: query_by_midpoint: true
shared_camera: true
camera_type: SIMPLE_RADIAL
max_query_pts: 1024
init_window_size: 6
window_size: 6
joint_BA_interval: 6
grid_based_sample: false
model_name: vggsfm_v2_0_0
seed: 0
img_size: 1024
debug: false
center_order: false
mixed_precision: fp16
extract_color: true
filter_invalid_frame: true
comple_nonvis: true
query_frame_num: 8
robust_refine: 2
BA_iters: 1
fine_tracking: true
load_gt: false
viz_visualize: false
gr_visualize: true
fmat_thres: 4.0
max_reproj_error: 4.0
init_max_reproj_error: 4.0
dense_depth: false
avg_pose: true
save_to_disk: true
SCENE_DIR: /home/user/Videos/test/cut/IMG_3135_cut_output_25fps
resume_ckpt: ckpt/vggsfm_v2_0_0.bin
auto_download_ckpt: true
query_method: aliked
use_poselib: true
shift_point2d_to_original_res: false
make_reproj_video: false
visual_tracks: true
visual_query_points: false
visual_dense_point_cloud: false
query_by_interval: false
concat_extra_points: false
extra_pt_pixel_interval: -1
extra_by_neighbor: -1
MODEL:
  _target_: vggsfm.models.VGGSfM
  TRACK:
    _target_: vggsfm.models.TrackerPredictor
    efficient_corr: false
    COARSE:
      stride: 4
      down_ratio: 2
      FEATURENET:
        _target_: vggsfm.models.BasicEncoder
      PREDICTOR:
        _target_: vggsfm.models.BaseTrackerPredictor
    FINE:
      FEATURENET:
        _target_: vggsfm.models.ShallowEncoder
      PREDICTOR:
        _target_: vggsfm.models.BaseTrackerPredictor
        depth: 4
        corr_levels: 3
        corr_radius: 3
        latent_dim: 32
        hidden_size: 256
        fine: true
        use_spaceatt: false
  CAMERA:
    _target_: vggsfm.models.CameraPredictor
  TRIANGULAE:
    _target_: vggsfm.models.Triangulator

Building VGGSfM
Using cache found in /home/user/.cache/torch/hub/facebookresearch_dinov2_main
/home/user/.cache/torch/hub/facebookresearch_dinov2_main/dinov2/layers/swiglu_ffn.py:51: UserWarning: xFormers is not available (SwiGLU)
  warnings.warn("xFormers is not available (SwiGLU)")
/home/user/.cache/torch/hub/facebookresearch_dinov2_main/dinov2/layers/attention.py:33: UserWarning: xFormers is not available (Attention)
  warnings.warn("xFormers is not available (Attention)")
/home/user/.cache/torch/hub/facebookresearch_dinov2_main/dinov2/layers/block.py:40: UserWarning: xFormers is not available (Block)
  warnings.warn("xFormers is not available (Block)")
[2025-03-20 17:57:52,780][dinov2][INFO] - using MLP layer as FFN
VGGSfM built successfully
Data size of Sequence: 1
Run Sparse Reconstruction for Scene IMG_3135_cut_output_25fps
Predicting tracks with query_index = 2
Predicting tracks with query_index = 0
Predicting tracks with query_index = 5
Predicting tracks with query_index = 1
Predicting tracks with query_index = 3
Predicting tracks with query_index = 4
[rawvideo @ 0x167bb080] Stream #0: not enough frames to estimate rate; consider increasing probesize
Video saved to /home/user/Videos/test/cut/IMG_3135_cut_output_25fps/visuals/track.mp4
/home/user/PycharmProjects/vggsfm/vggsfm/runners/runner.py:489: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(dtype=torch.float32):
/home/user/PycharmProjects/vggsfm/vggsfm/models/triangulator.py:74: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(dtype=torch.float32):
/home/user/PycharmProjects/vggsfm/vggsfm/utils/triangulation.py:653: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(dtype=torch.float32):
I20250320 17:58:18.721911 138005444724224 misc.cc:198] 
==============================================================================
Global bundle adjustment
==============================================================================
I20250320 17:58:19.687546 138005444724224 timer.cc:91] Elapsed time: 0.016 [minutes]
Finished init BA
Finished init refine pose
I20250320 17:58:20.568237 138005444724224 misc.cc:198] 
==============================================================================
Global bundle adjustment
==============================================================================
I20250320 17:58:20.586360 138005444724224 timer.cc:91] Elapsed time: 0.000 [minutes]
Finished track triangulation and BA
Frame 0 only has 34 geo_vis inliers
Frame 1 only has 35 geo_vis inliers
Frame 2 only has 35 geo_vis inliers
Frame 3 only has 35 geo_vis inliers
Frame 4 only has 35 geo_vis inliers
Frame 5 only has 35 geo_vis inliers
I20250320 17:58:21.668247 138005444724224 misc.cc:198] 
==============================================================================
Global bundle adjustment
==============================================================================
I20250320 17:58:24.054803 138005444724224 timer.cc:91] Elapsed time: 0.040 [minutes]
Finished robust refine 0
I20250320 17:58:24.918098 138005444724224 misc.cc:198] 
==============================================================================
Global bundle adjustment
==============================================================================
I20250320 17:58:26.237605 138005444724224 timer.cc:91] Elapsed time: 0.022 [minutes]
Finished robust refine 1
Running iterative BA by 1 times
I20250320 17:58:27.043048 138005444724224 misc.cc:198] 
==============================================================================
Global bundle adjustment
==============================================================================
I20250320 17:58:28.978010 138005444724224 bundle_adjustment.cc:866] 
Bundle adjustment report:
    Residuals : 52334
   Parameters : 13168
   Iterations : 101
         Time : 1.92286 [s]
 Initial cost : 0.563932 [px]
   Final cost : 0.268285 [px]
  Termination : No convergence

I20250320 17:58:28.978033 138005444724224 timer.cc:91] Elapsed time: 0.032 [minutes]
Finished iterative BA 0
Processing window from 6 to 9
Predicting tracks with query_index = 0
No valid frame, step back
Moving window failed, trying again. (This should not happen in most cases)
Processing window from 5 to 11
Error executing job with overrides: ['SCENE_DIR=/home/user/Videos/test/cut/IMG_3135_cut_output_25fps', 'gr_visualize=True', 'visual_tracks=True', 'shared_camera=True', 'query_frame_num=8', 'camera_type=SIMPLE_RADIAL', 'center_order=False']
Traceback (most recent call last):
  File "/home/user/PycharmProjects/vggsfm/video_demo.py", line 74, in demo_fn
    predictions = vggsfm_runner.run(
                  ^^^^^^^^^^^^^^^^^^
  File "/home/user/PycharmProjects/vggsfm/vggsfm/runners/video_runner.py", line 173, in run
    start_idx, end_idx, move_success, _ = self.move_window(
                                          ^^^^^^^^^^^^^^^^^
  File "/home/user/PycharmProjects/vggsfm/vggsfm/runners/video_runner.py", line 671, in move_window
    self.frame_dict[frame_idx]["extri"]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'extri'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
